### ISSUE TITLE
NEVO library not existent

### ISSUE THREAD

**Issue by master-puller** [MaximilienLC/nra#1]
The [link](https://github.com/MaximilienLC/nevo) referred to in the readme of both the [nra](https://github.com/MaximilienLC/nra)  and [ssn](https://github.com/MaximilienLC/ssn) exist, or is private.

**Comment by MaximilienLC** [comment]
Hehe, I'm planning on putting it up tomorrow or monday, didn't anticipate I'd grab someone's attention today :laughing:

**Comment by MaximilienLC** [comment]
Good now :wink:
